# Generated by Django 5.0.7 on 2025-01-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='date_added',
        ),
        migrations.AddField(
            model_name='problem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
