# Generated by Django 5.0.7 on 2025-01-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0004_remove_problem_date_added_problem_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
