# Generated by Django 5.0.7 on 2025-01-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0005_alter_problem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_top_positions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
