# Generated by Django 5.0.7 on 2025-01-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0007_remove_customuser_daily_top_positions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_leaderboard', models.BooleanField(default=False)),
            ],
        ),
    ]
